"""SQLite persistence for connected-network security score history."""

import json
import os
import shutil
import sqlite3
import sys
import hashlib
import hmac
import re
import secrets
from contextlib import closing
from datetime import datetime, timedelta, timezone
from pathlib import Path


if getattr(sys, "frozen", False):
    app_data = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
    DATABASE_PATH = app_data / "WISE" / "wise_scans.db"
else:
    # Keep source-run history with this checkout. The database is ignored by Git,
    # so a fresh clone starts empty while rescans in this checkout remain saved.
    DATABASE_PATH = Path(__file__).with_name("wise_scans.db")


def _database_template_path():
    if getattr(sys, "frozen", False):
        bundle_root = Path(getattr(sys, "_MEIPASS", Path(sys.executable).parent))
        return bundle_root / "data" / "wise_scans.db"
    return Path(__file__).with_name("data") / "wise_scans.db"


DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
SESSION_TTL_SECONDS = 30 * 24 * 60 * 60


def _connect():
    if DATABASE_URL:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as error:
            raise RuntimeError("Install psycopg[binary] to connect to the shared PostgreSQL database.") from error
        return _PostgresConnection(psycopg.connect(DATABASE_URL, row_factory=dict_row))
    DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(DATABASE_PATH)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA busy_timeout = 5000")
    connection.execute("PRAGMA foreign_keys = ON")
    connection.execute("PRAGMA secure_delete = ON")
    return connection


class _PostgresConnection:
    """Small SQLite-compatible adapter for the app's parameterized SQL."""
    def __init__(self, connection):
        self.connection = connection

    def __enter__(self):
        self.connection.__enter__()
        return self

    def __exit__(self, *args):
        return self.connection.__exit__(*args)

    def execute(self, sql, params=()):
        sql = sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        sql = sql.replace("INTEGER PRIMARY KEY", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        sql = sql.replace("INTEGER REFERENCES", "BIGINT REFERENCES")
        sql = sql.replace("INTEGER", "BIGINT")
        sql = sql.replace("TEXT", "TEXT")
        sql = sql.replace("?", "%s")
        sql = sql.replace("user_id IS %s", "user_id IS NOT DISTINCT FROM %s")
        sql = sql.replace("user_id IS NOT %s", "user_id IS DISTINCT FROM %s")
        return self.connection.execute(sql, params)

    def close(self):
        self.connection.close()


def initialize_database():
    if DATABASE_URL:
        with closing(_connect()) as connection, connection:
            connection.execute("""CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL, username_key TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL, created_at TEXT NOT NULL)""")
            connection.execute("""CREATE TABLE IF NOT EXISTS sessions (
                token_hash TEXT PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at TEXT NOT NULL)""")
            connection.execute("""CREATE TABLE IF NOT EXISTS device_snapshots (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                scanned_at TEXT NOT NULL, interface TEXT NOT NULL, subnet TEXT NOT NULL,
                gateway_ip TEXT, devices_json TEXT NOT NULL DEFAULT '[]')""")
            connection.execute("""CREATE TABLE IF NOT EXISTS scans (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                scanned_at TEXT NOT NULL, ssid TEXT NOT NULL DEFAULT '<Unknown>',
                network_key TEXT NOT NULL DEFAULT '<Unknown>', score INTEGER NOT NULL DEFAULT 0,
                protocol_score INTEGER NOT NULL DEFAULT 0, company_score INTEGER NOT NULL DEFAULT 0,
                other_score INTEGER NOT NULL DEFAULT 0, user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
                connection_json TEXT NOT NULL DEFAULT '{}', score_json TEXT NOT NULL DEFAULT '{}',
                recommended_channel INTEGER, congestion_status TEXT,
                environment_json TEXT NOT NULL DEFAULT '{}')""")
            connection.execute("CREATE INDEX IF NOT EXISTS idx_scans_user_network_time ON scans(user_id, network_key, scanned_at, id)")
            connection.execute("CREATE INDEX IF NOT EXISTS idx_device_snapshots_user_time ON device_snapshots(user_id, scanned_at, id)")
        return
    DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
    template_path = _database_template_path()
    if not DATABASE_PATH.exists() and template_path.is_file():
        shutil.copyfile(template_path, DATABASE_PATH)
    with closing(_connect()) as connection, connection:
        connection.execute(
            """CREATE TABLE IF NOT EXISTS scans (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                scanned_at TEXT NOT NULL,
                ssid TEXT NOT NULL DEFAULT '<Unknown>',
                network_key TEXT NOT NULL DEFAULT '<Unknown>',
                score INTEGER NOT NULL DEFAULT 0,
                protocol_score INTEGER NOT NULL DEFAULT 0,
                company_score INTEGER NOT NULL DEFAULT 0,
                other_score INTEGER NOT NULL DEFAULT 0,
                connection_json TEXT NOT NULL DEFAULT '{}',
                score_json TEXT NOT NULL DEFAULT '{}',
                recommended_channel INTEGER,
                congestion_status TEXT,
                environment_json TEXT NOT NULL DEFAULT '{}'
            )"""
        )
        connection.execute(
            """CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT NOT NULL,
                username_key TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                created_at TEXT NOT NULL
            )"""
        )
        connection.execute(
            """CREATE TABLE IF NOT EXISTS sessions (
                token_hash TEXT PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at TEXT NOT NULL
            )"""
        )
        connection.execute(
            """CREATE TABLE IF NOT EXISTS device_snapshots (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                scanned_at TEXT NOT NULL,
                interface TEXT NOT NULL,
                subnet TEXT NOT NULL,
                gateway_ip TEXT,
                devices_json TEXT NOT NULL DEFAULT '[]'
            )"""
        )
        columns = {row["name"] for row in connection.execute("PRAGMA table_info(scans)")}
        if "user_id" not in columns:
            connection.execute("ALTER TABLE scans ADD COLUMN user_id INTEGER REFERENCES users(id) ON DELETE CASCADE")
        for name, definition in (
                ("ssid", "TEXT NOT NULL DEFAULT '<Unknown>'"),
            ("network_key", "TEXT NOT NULL DEFAULT '<Unknown>'"),
            ("score", "INTEGER NOT NULL DEFAULT 0"),
            ("protocol_score", "INTEGER NOT NULL DEFAULT 0"),
            ("company_score", "INTEGER NOT NULL DEFAULT 0"),
            ("other_score", "INTEGER NOT NULL DEFAULT 0"),
            ("connection_json", "TEXT NOT NULL DEFAULT '{}'"),
            ("score_json", "TEXT NOT NULL DEFAULT '{}'"),
            ("recommended_channel", "INTEGER"),
            ("congestion_status", "TEXT"),
            ("environment_json", "TEXT NOT NULL DEFAULT '{}'"),
        ):
            if name not in columns:
                connection.execute(f"ALTER TABLE scans ADD COLUMN {name} {definition}")
        # An earlier WISE version stored nearby networks in a separate table.
        # Backfill compatible SSIDs before adding the rescan lookup index.
        connection.execute(
            "UPDATE scans SET network_key = 'ssid:' || lower(ssid) "
            "WHERE ssid <> '<Unknown>' AND "
            "(network_key = '<Unknown>' OR network_key = lower(ssid))"
        )
        connection.execute(
            "CREATE INDEX IF NOT EXISTS idx_scans_user_network_time ON scans(user_id, network_key, scanned_at, id)"
        )
        connection.execute(
            "CREATE INDEX IF NOT EXISTS idx_device_snapshots_user_time ON device_snapshots(user_id, scanned_at, id)"
        )


def _password_hash(password, salt=None):
    salt = salt or secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, 600_000)
    return f"pbkdf2_sha256$600000${salt.hex()}${digest.hex()}"


def _is_username_conflict(error):
    if isinstance(error, sqlite3.IntegrityError):
        return "username_key" in str(error)
    return getattr(error, "sqlstate", None) == "23505"


def register_user(username, password):
    """Create a unique account; password is stored only as a salted hash."""
    username = username.strip()
    if not re.fullmatch(r"[A-Za-z0-9_.-]{3,32}", username):
        raise ValueError("Username must be 3–32 characters using letters, numbers, dot, dash, or underscore.")
    if len(password) < 8:
        raise ValueError("Password must be at least 8 characters long.")
    key = username.casefold()
    with closing(_connect()) as connection, connection:
        try:
            cursor = connection.execute(
                "INSERT INTO users (username, username_key, password_hash, created_at) VALUES (?, ?, ?, ?) RETURNING id",
                (username, key, _password_hash(password), datetime.now().astimezone().isoformat(timespec="seconds")),
            )
        except Exception as error:
            if _is_username_conflict(error):
                raise ValueError("That username is already registered.") from error
            raise
        user_id = cursor.fetchone()["id"] if DATABASE_URL else cursor.lastrowid
        cursor.close()
        return {"id": user_id, "username": username}


def authenticate_user(username, password):
    key = username.strip().casefold()
    with closing(_connect()) as connection:
        row = connection.execute("SELECT * FROM users WHERE username_key = ?", (key,)).fetchone()
    if row is None:
        return None
    try:
        _, rounds, salt_hex, expected_hex = row["password_hash"].split("$")
        actual = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), bytes.fromhex(salt_hex), int(rounds))
        return {"id": row["id"], "username": row["username"]} if hmac.compare_digest(actual.hex(), expected_hex) else None
    except (ValueError, TypeError):
        return None


def get_user(user_id):
    with closing(_connect()) as connection:
        row = connection.execute("SELECT id, username FROM users WHERE id = ?", (user_id,)).fetchone()
    return {"id": row["id"], "username": row["username"]} if row else None


def change_user_password(user_id, current_password, new_password, session_token=None):
    if len(new_password) < 8:
        raise ValueError("Password must be at least 8 characters long.")
    with closing(_connect()) as connection, connection:
        row = connection.execute("SELECT password_hash FROM users WHERE id = ?", (user_id,)).fetchone()
        if row is None:
            raise ValueError("Account no longer exists.")
        try:
            _, rounds, salt_hex, expected_hex = row["password_hash"].split("$")
            actual = hashlib.pbkdf2_hmac("sha256", current_password.encode("utf-8"),
                                         bytes.fromhex(salt_hex), int(rounds))
        except (ValueError, TypeError):
            raise ValueError("Current password is incorrect.")
        if not hmac.compare_digest(actual.hex(), expected_hex):
            raise ValueError("Current password is incorrect.")
        connection.execute("UPDATE users SET password_hash = ? WHERE id = ?", (_password_hash(new_password), user_id))
        if session_token:
            connection.execute("DELETE FROM sessions WHERE user_id = ? AND token_hash <> ?",
                               (user_id, _session_token_hash(session_token)))
        else:
            connection.execute("DELETE FROM sessions WHERE user_id = ?", (user_id,))


def delete_user(user_id, current_password):
    with closing(_connect()) as connection, connection:
        row = connection.execute("SELECT password_hash FROM users WHERE id = ?", (user_id,)).fetchone()
        if row is None:
            return False
        try:
            _, rounds, salt_hex, expected_hex = row["password_hash"].split("$")
            actual = hashlib.pbkdf2_hmac("sha256", current_password.encode("utf-8"),
                                         bytes.fromhex(salt_hex), int(rounds))
        except (ValueError, TypeError):
            raise ValueError("Password is incorrect.")
        if not hmac.compare_digest(actual.hex(), expected_hex):
            raise ValueError("Password is incorrect.")
        connection.execute("DELETE FROM users WHERE id = ?", (user_id,))
        return True


def _session_token_hash(token):
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def create_session(token, user_id, ttl_seconds=SESSION_TTL_SECONDS):
    expires_at = (datetime.now(timezone.utc) + timedelta(seconds=ttl_seconds)).isoformat(timespec="seconds")
    with closing(_connect()) as connection, connection:
        connection.execute("DELETE FROM sessions WHERE expires_at <= ?", (datetime.now(timezone.utc).isoformat(timespec="seconds"),))
        connection.execute(
            "INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, ?)",
            (_session_token_hash(token), user_id, expires_at),
        )


def get_session_user_id(token):
    token_hash = _session_token_hash(token)
    now = datetime.now(timezone.utc)
    with closing(_connect()) as connection, connection:
        row = connection.execute(
            "SELECT user_id, expires_at FROM sessions WHERE token_hash = ?", (token_hash,)
        ).fetchone()
        if row is None:
            return None
        if datetime.fromisoformat(row["expires_at"]) <= now:
            connection.execute("DELETE FROM sessions WHERE token_hash = ?", (token_hash,))
            return None
        return row["user_id"]


def delete_session(token):
    with closing(_connect()) as connection, connection:
        cursor = connection.execute(
            "DELETE FROM sessions WHERE token_hash = ?", (_session_token_hash(token),)
        )
        return cursor.rowcount > 0


def save_scan(connection_info, score_info, update_id=None, user_id=None, separate=False):
    """Save a scan or update its user-entered assessment; return its id and prior scan."""
    ssid = str(connection_info.get("ssid", "<Unknown>"))
    bssid = str(connection_info.get("bssid") or "").strip().casefold()
    if ssid.strip().casefold() in ("", "<hidden>", "<unknown>"):
        network_key = f"bssid:{bssid}" if bssid else f"hidden:{datetime.now().timestamp()}"
    else:
        network_key = f"ssid:{ssid.casefold()}"
    scanned_at = datetime.now().astimezone().isoformat(timespec="seconds")
    environment = connection_info.get("environment") or {}
    environment_json = json.dumps(environment, ensure_ascii=False)
    recommended_channel = environment.get("recommended_channel")
    congestion_status = environment.get("status")
    with closing(_connect()) as connection, connection:
        previous = connection.execute(
            "SELECT * FROM scans WHERE network_key = ? AND user_id IS ? ORDER BY scanned_at DESC, id DESC LIMIT 1",
            (network_key, user_id),
        ).fetchone()
        existing = None
        if update_id is not None:
            existing = connection.execute(
                "SELECT * FROM scans WHERE id = ? AND user_id IS ?", (update_id, user_id)
            ).fetchone()
        elif previous is not None and not separate:
            existing = previous

        if existing is not None and existing["network_key"] == network_key:
            prior = dict(existing)
            connection.execute(
                """UPDATE scans SET scanned_at = ?, score = ?, protocol_score = ?, company_score = ?, other_score = ?,
                   connection_json = ?, score_json = ?, recommended_channel = ?, congestion_status = ?,
                   environment_json = ? WHERE id = ? AND user_id IS ?""",
                (scanned_at, score_info["total"], score_info["protocol"], score_info["company_and_password"],
                 score_info["other"], json.dumps(connection_info, ensure_ascii=False),
                 json.dumps(score_info, ensure_ascii=False), recommended_channel, congestion_status,
                 environment_json, existing["id"], user_id),
            )
            return {"id": existing["id"], "previous": prior, "updated": True}
        cursor = connection.execute(
            """INSERT INTO scans
             (scanned_at, ssid, network_key, score, protocol_score, company_score, other_score, user_id,
                connection_json, score_json, recommended_channel, congestion_status, environment_json)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""" + (" RETURNING id" if DATABASE_URL else ""),
            (scanned_at, ssid, network_key, score_info["total"], score_info["protocol"],
             score_info["company_and_password"], score_info["other"], user_id,
             json.dumps(connection_info, ensure_ascii=False), json.dumps(score_info, ensure_ascii=False),
             recommended_channel, congestion_status, environment_json),
        )
        scan_id = cursor.fetchone()["id"] if DATABASE_URL else cursor.lastrowid
        return {"id": scan_id, "previous": dict(previous) if previous else None}


def list_scans(user_id=None):
    with closing(_connect()) as connection, connection:
        return [dict(row) for row in connection.execute(
            "SELECT id, scanned_at, ssid, network_key, score, protocol_score, company_score, other_score "
            "FROM scans WHERE user_id IS ? ORDER BY scanned_at DESC, id DESC", (user_id,)
        )]


def get_scan(scan_id, user_id=None):
    with closing(_connect()) as connection, connection:
        row = connection.execute("SELECT * FROM scans WHERE id = ? AND user_id IS ?", (scan_id, user_id)).fetchone()
        if row is None:
            return None
        result = dict(row)
        connection_info = json.loads(result.pop("connection_json"))
        score_details = json.loads(result.pop("score_json"))
        result["environment"] = json.loads(result.pop("environment_json"))
        result["connection"] = connection_info if isinstance(connection_info, dict) else {}
        if isinstance(score_details, dict) and score_details:
            result["score_details"] = score_details
        else:
            protocol = result["protocol_score"]
            company = result["company_score"]
            other = result["other_score"]
            result["score_details"] = {
                "total": result["score"],
                "protocol": protocol,
                "company_and_password": company,
                "other": other,
                "company_network": False,
                "password_policy_ok": False,
                "breakdown": [
                    {"category": "Security protocol", "earned": protocol, "possible": 60,
                     "note": "Details were not stored in this older scan."},
                    {"category": "Company SSID/password", "earned": company, "possible": 20,
                     "note": "Details were not stored in this older scan."},
                    {"category": "Other safeguards", "earned": other, "possible": 20,
                     "note": "Details were not stored in this older scan."},
                ],
            }
        return result


def delete_scan(scan_id, user_id=None):
    with closing(_connect()) as connection, connection:
        cursor = connection.execute("DELETE FROM scans WHERE id = ? AND user_id IS ?", (scan_id, user_id))
        return cursor.rowcount > 0


def delete_all_scans(user_id=None):
    with closing(_connect()) as connection, connection:
        cursor = connection.execute("DELETE FROM scans WHERE user_id IS ?", (user_id,))
        return cursor.rowcount


def save_device_snapshot(user_id, snapshot):
    scanned_at = datetime.now().astimezone().isoformat(timespec="seconds")
    devices = [dict(device) for device in snapshot.get("devices", [])]
    with closing(_connect()) as connection, connection:
        previous = connection.execute(
            "SELECT devices_json FROM device_snapshots WHERE user_id = ? ORDER BY scanned_at DESC, id DESC LIMIT 1",
            (user_id,),
        ).fetchone()
        has_previous = previous is not None
        known_macs = set()
        if previous:
            known_macs = {str(device.get("mac", "")).casefold()
                          for device in json.loads(previous["devices_json"])}
        for device in devices:
            mac = str(device.get("mac", "")).casefold()
            device["is_new"] = bool(has_previous and mac and mac != "unknown" and mac not in known_macs)
        values = (user_id, scanned_at, str(snapshot.get("interface", "Unknown")),
                  str(snapshot.get("subnet", "Unknown")), snapshot.get("gateway_ip"),
                  json.dumps(devices, ensure_ascii=False))
        cursor = connection.execute(
            "INSERT INTO device_snapshots (user_id, scanned_at, interface, subnet, gateway_ip, devices_json) "
            "VALUES (?, ?, ?, ?, ?, ?)" + (" RETURNING id" if DATABASE_URL else ""), values,
        )
        snapshot_id = cursor.fetchone()["id"] if DATABASE_URL else cursor.lastrowid
        cursor.close()
    return {"id": snapshot_id, "scanned_at": scanned_at, "interface": values[2],
            "subnet": values[3], "gateway_ip": values[4], "devices": devices}


def latest_device_snapshot(user_id):
    with closing(_connect()) as connection:
        row = connection.execute(
            "SELECT * FROM device_snapshots WHERE user_id = ? ORDER BY scanned_at DESC, id DESC LIMIT 1",
            (user_id,),
        ).fetchone()
    if row is None:
        return None
    result = dict(row)
    result["devices"] = json.loads(result.pop("devices_json"))
    return result
